spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 342a3a04152e77a49053
            clientSecret: 30544be9c49e99decff264f5945c18353b591e97

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

server:
  port: 8080
